# Generated by Django 4.1.2 on 2022-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORD_ID', models.CharField(max_length=100)),
                ('ORD_DT', models.DateField()),
                ('QT_ORDD', models.IntegerField()),
            ],
        ),
    ]
